[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
language-servers = ["pyright", "ruff"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=88"
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]


[language-server.pyright.config]
reportMissingTypeStubs = false
inlay-hints = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config]
settings = {args = []}

#Kotlin
[[language]]
name = "kotlin"
scope = "source.kotlin"
file-types = ["kt", "kts"]
# You might include common project files as roots (adjust as needed)
roots = ["build.gradle", "build.gradle.kts", "settings.gradle", ".git"]
indent = { tab-width = 4, unit = "    " }
auto-format = true


[language.formatter]
command = "ktfmt"
args = ["-"]  # Reads from STDIN and writes formatted code to STDOUT


[language-server.kotlin-language-server]
command = "kotlin-language-server"
args = ["--stdio"]

# Optionally, if the Kotlin language server supports additional configuration,
# you can include a config section. For example:
[language-server.kotlin-language-server.config]
# Add custom configuration options here (if any)


[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
indent = { tab-width = 4, unit = "	"}
auto-format = true


[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "hcl"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "tfvars"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true
