theme = "retro_kamesh" 
[editor]
# mouse = false
shell = ["zsh", "-cu"]
line-number = "relative"
preview-completion-insert = true
bufferline = "always"
cursorline = true
completion-timeout = 150
color-modes = true
# automic-save = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spacer", "spinner", "file-modification-indicator", "spacer", "version-control"]
center = ["file-name", "spacer", "spinner", "file-absolute-path"]  
right = ["diagnostics", "selections", "position", "total-line-numbers", "position-percentage", "file-encoding", "file-line-ending", "file-type", "read-only-indicator", "register"]

[editor.indent-guides]
character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽"
render = true

[editor.whitespace.render]
tab = "all"
tabpad = "all"
newline = "none"

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false
display-progress-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 3000


[editor.inline-diagnostics]
cursor-line	= "hint"
# other-lines = "warning"

# [editor.gutters]
# layout = ["diff", "diagnostics", "line-numbers", "spacer"]


[keys.normal]
y = "yank_main_selection_to_clipboard" 
p = "paste_clipboard_before"  
"esc" = ["collapse_selection", "keep_primary_selection", ":w"]
# Add a new line above and enter normal mode
"ret" = ["goto_word"]
"A-s" = "save_selection"
i = "move_visual_line_up"
k = "move_visual_line_down"
j = "move_char_left"
l = "move_char_right"
I = ["insert_mode"]
C-left = "move_prev_word_start"
C-right = "move_next_word_start"
C-up = "move_line_up"
C-down = "move_line_down"
"C-l" = ":sh zellij run -f -x 5%% -y 5%% --width 90%% --height 90%% -- sh -c 'lazygit && zellij action close-pane'"
"C-p" = "signature_help"

# [editor.soft-wrap]
# enable = true

[keys.insert]
j = { k = ["normal_mode", ":w"] }
C-left = "move_prev_word_start"
C-right = "move_next_word_start"
C-up = "move_line_up"
C-down = "move_line_down"

[keys.select]
y = "yank_main_selection_to_clipboard" 
p = "paste_clipboard_before" 
